# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.3.8.{build}

# branches to build
branches:
  # whitelist
  only:
    - default

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "0.3.8.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

# crontab: 0 21 * * *